
O conteúdo desse arquivo está no link abaixo.

Gentileza copiar e substituir as informações necessárias para o ambiente de PRODUÇÃO.

https://localiza.visualstudio.com/Infraestrutura%20-%20Localiza%20Agile/_git/TI.Container.Chart.NetCore-3.X?path=%2FConfig%2Fvalues-%5Bambiente%5D.yml&version=GBmaster&_a=contents